/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProdavnicaRouteImport } from './routes/prodavnica'
import { Route as ONamaRouteImport } from './routes/o-nama'
import { Route as NaplataRouteImport } from './routes/naplata'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProizvodSkuRouteImport } from './routes/proizvod.$sku'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdavnicaRoute = ProdavnicaRouteImport.update({
  id: '/prodavnica',
  path: '/prodavnica',
  getParentRoute: () => rootRouteImport,
} as any)
const ONamaRoute = ONamaRouteImport.update({
  id: '/o-nama',
  path: '/o-nama',
  getParentRoute: () => rootRouteImport,
} as any)
const NaplataRoute = NaplataRouteImport.update({
  id: '/naplata',
  path: '/naplata',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProizvodSkuRoute = ProizvodSkuRouteImport.update({
  id: '/proizvod/$sku',
  path: '/proizvod/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/naplata': typeof NaplataRoute
  '/o-nama': typeof ONamaRoute
  '/prodavnica': typeof ProdavnicaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proizvod/$sku': typeof ProizvodSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/naplata': typeof NaplataRoute
  '/o-nama': typeof ONamaRoute
  '/prodavnica': typeof ProdavnicaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proizvod/$sku': typeof ProizvodSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/naplata': typeof NaplataRoute
  '/o-nama': typeof ONamaRoute
  '/prodavnica': typeof ProdavnicaRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/proizvod/$sku': typeof ProizvodSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/naplata'
    | '/o-nama'
    | '/prodavnica'
    | '/services'
    | '/sitemap.xml'
    | '/proizvod/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/naplata'
    | '/o-nama'
    | '/prodavnica'
    | '/services'
    | '/sitemap.xml'
    | '/proizvod/$sku'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/naplata'
    | '/o-nama'
    | '/prodavnica'
    | '/services'
    | '/sitemap.xml'
    | '/proizvod/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  NaplataRoute: typeof NaplataRoute
  ONamaRoute: typeof ONamaRoute
  ProdavnicaRoute: typeof ProdavnicaRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProizvodSkuRoute: typeof ProizvodSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodavnica': {
      id: '/prodavnica'
      path: '/prodavnica'
      fullPath: '/prodavnica'
      preLoaderRoute: typeof ProdavnicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nama': {
      id: '/o-nama'
      path: '/o-nama'
      fullPath: '/o-nama'
      preLoaderRoute: typeof ONamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/naplata': {
      id: '/naplata'
      path: '/naplata'
      fullPath: '/naplata'
      preLoaderRoute: typeof NaplataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proizvod/$sku': {
      id: '/proizvod/$sku'
      path: '/proizvod/$sku'
      fullPath: '/proizvod/$sku'
      preLoaderRoute: typeof ProizvodSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  NaplataRoute: NaplataRoute,
  ONamaRoute: ONamaRoute,
  ProdavnicaRoute: ProdavnicaRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProizvodSkuRoute: ProizvodSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
